### ISSUE TITLE
Clonetype and file size limit setting ignored in application

### ISSUE THREAD

**Issue by s-andrews** [antigenomics/vdjviz#27]
After a bit of playing I've got your server up and running, but couldn't get any files to load.  The reason was that they were being rejected by the clonetype limit as they had >100000 clonetypes in them or were too large.

There is an option to change this in the conf file, but that doesn't actually stop the file from being rejected, but it does change the error message so I get an error saying I need to load a file with less than 1,000,000 clonetypes (for example), but the log file says  Loaded sample 2.A2-i129 with 540240 clonotypes.  Even if you set the limit to 0 for unlimited I get an error saying you need less than 0 clonetypes.  The same thing seems to be true of the file sizes - you don't get a specific report, but everything over the default size is rejected even if the conf file has been modified.

**Comment by bvdmitri** [comment]
Hello !
Thank you for your feedback!
The fact is that the configuration file is used only then the application is creating user's account. After that server uses your account's limits for uploading files. This is done in order to use different limits for different accounts. So if you change the default configuration that does not affect already created accounts, you can create a new account, or you can change your limits in database.

For MySQL database console write:
`use vdjviz;`
`update account set privelegies=1;`

This commands will remove all limits from your accounts.

About invalid error message: there was a typo in our code that was already fixed. Thank you!
